---
# tasks file for ansible-unbound
- ansible.builtin.import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- ansible.builtin.import_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- ansible.builtin.import_tasks: config_unbound.yml
  when: config_unbound

...
